--------------------------------------------------------
--  文件已创建 - 星期二-六月-28-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FI_ZHCGMAINTYPE
--------------------------------------------------------

  CREATE TABLE "BMSInspection"."dbo"."CG_ZHCGMAINTYPE"
     (
     "MAINTYPEID" VARCHAR(20),
  	"MAINTYPECODE" VARCHAR(20),
  	"MAINTYPENAME" VARCHAR(20),
  	"EVENTTYPEID" VARCHAR(20),
  	"UNIQUECODE" VARCHAR(20)
     )
--   COMMENT ON COLUMN "YZSCM"."FI_ZHCGMAINTYPE"."MAINTYPEID" IS '大类类型标识';
--
--   COMMENT ON COLUMN "YZSCM"."FI_ZHCGMAINTYPE"."MAINTYPECODE" IS '大类类型代码';
--
--   COMMENT ON COLUMN "YZSCM"."FI_ZHCGMAINTYPE"."MAINTYPENAME" IS '大类类型名称';
--
--   COMMENT ON COLUMN "YZSCM"."FI_ZHCGMAINTYPE"."EVENTTYPEID" IS '问题类型标识';
--
--   COMMENT ON COLUMN "YZSCM"."FI_ZHCGMAINTYPE"."UNIQUECODE" IS '唯一代码';
--REM INSERTING into YZSCM.FI_ZHCGMAINTYPE
--SET DEFINE OFF;
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (3,'1','市容环境',1,'101');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (4,'2','宣传广告',1,'102');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (5,'3','施工管理',1,'103');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (6,'4','突发事件',1,'104');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (7,'5','街面秩序',1,'105');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (8,'21','扩展事件',1,'121');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (9,'22','投诉',1,'122');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (10,'23','咨询',1,'123');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (11,'1','市政公用设施',2,'201');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (12,'2','道路交通设施',2,'202');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (13,'3','市容环境',2,'203');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (14,'4','园林绿化',2,'204');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (15,'5','房屋建筑',2,'205');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (16,'6','其他设施',2,'206');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (17,'21','扩展部件',2,'221');
Insert into "BMSInspection"."dbo"."CG_ZHCGMAINTYPE" (MAINTYPEID,MAINTYPECODE,MAINTYPENAME,EVENTTYPEID,UNIQUECODE) values (204,'24','数据普查专项',1,'124');

